---
title: "Detailed description of one gene cluster"
subtitle: "A subroutine of the gene clustering procedure"
author: "Jim Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    toc: yes
---

```{r global_setup, include=FALSE}
knitr::opts_chunk$set(dpi=300, fig.pos="H", fig.width=8, fig.height=6, dev=c('png', 'pdf'), echo=FALSE, warning=FALSE, message=FALSE);

library(awsomics);
library(gplots);
library(knitr);

if (!exists('name')) stop("cluster name not given\n"); # the name of the cluster
#if (!exists('path')) stop("output file path not given\n"); # the path to output files
if (!exists('mtrx')) stop("data matrix not given\n"); # the data matrix of gene clusters
if (!exists('anno')) stop("gene annotation not given\n"); # the annotation of each row in the data matrix
if (!exists('grps')) stop("sample groups not given\n"); # the sample groups corresponding to the data matrix columns

#if (!file.exists(path)) dir.create(path, recursive = TRUE);
```

# Cluster `r name`


## Data visualization

**Figure** Hierarchical clustering of samples using all genes of the cluster

```{r clustering, include=TRUE, out.width="600px",}
plot(hclust(as.dist(1-cor(mtrx))), main=name, xlab='Sample', sub=''); 
```

**Figure** Heatmap using all genes and samples

```{r heatmap, include=TRUE, out.width="800px", fig.height=8, fig.width=max(6, 0.05*nrow(mtrx))}
sortColumn<-function(ms, g) {
  corr<-as.vector(cor(rowMeans(ms[, g[[2]], drop=FALSE]), ms[, g[[1]], drop=FALSE]));
  g[[1]]<-g[[1]][order(corr)];
  for (i in 2:length(g)) {
    corr<-as.vector(cor(rowMeans(ms[, g[[i-1]], drop=FALSE]), ms[, grp[[i]], drop=FALSE]));
    g[[i]]<-g[[i]][rev(order(corr))]; 
  }
  ms[, as.vector(unlist(g))]; 
}
d<-sortColumn(mtrx, grps); 
rownames(d)<-paste(rownames(d), anno[rownames(d), 1], sep=':'); 
PlotColoredBlock(d, num.breaks = 127, groups=grp, key='Expression level'); 
abline(v=c(0, cumsum(sapply(grp, length))), lwd=1); 
```

***
_END OF DOCUMENT_